# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: disabled

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${hydra.runtime.choices.experiment}/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${hydra.runtime.choices.experiment}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
