_target_: src.datamodules.video_datamodule.VideoDataModule
train_batch_size: 16
val_batch_size: 1
num_workers: 4
pin_memory: False

data_train:
  _target_: src.datamodules.components.egoframe_dataset.Ego4DFrameDatasetV0
  video_root: ${oc.env:DATASET_DIR}/ego4d/v1/frame_540ss_fps1/
  max_interval: 5
  sample_per_video: True
  transform:
    _target_: src.datamodules.components.transforms.PairTransformV0
    base_size: 256
    crop_size: 224

data_val:
  _target_: src.datamodules.components.tapvid_datasets.TAPVidDAVISDataset
  path: ${oc.env:DATASET_DIR}/tapvid_davis/tapvid_davis.pkl
  transform:
    _target_: src.datamodules.components.tapvid_datasets.TapVidTransform
    size: [224, 224]

data_test:
  _target_: src.datamodules.components.tapvid_datasets.TAPVidDAVISDataset
  path: ${oc.env:DATASET_DIR}/tapvid_davis/tapvid_davis.pkl
  transform:
    _target_: src.datamodules.components.tapvid_datasets.TapVidTransform
    size: [224, 224]
